# Build Stage
FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
WORKDIR /app/cmd/app

ARG ARG_GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=${ARG_GOOGLE_CLIENT_ID}

ARG ARG_GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=${ARG_GOOGLE_CLIENT_SECRET}

ARG ARG_OPENWEATHER_API_KEY
ENV OPENWEATHER_API_KEY=${ARG_OPENWEATHER_API_KEY}

ARG ARG_REDIRECT_URI
ENV REDIRECT_URI=${ARG_REDIRECT_URI}

RUN go build -o main .

# Runtime Stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 5000
CMD ["./main"]