apiVersion: v1
kind: Secret
metadata:
  name: golang-weatherapp-secret
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ...
  GOOGLE_CLIENT_SECRET: ...
  OPENWEATHER_API_KEY: ...
  REDIRECT_URI: https://localhost:3000/callback
